// Generated by CoffeeScript 1.12.7
var Phil, count_words, expect, expect_element, find_children, ref, utils;

Phil = require('../Phil');

ref = utils = require('./utils'), expect = ref.expect, find_children = ref.find_children, expect_element = ref.expect_element, count_words = ref.count_words;

describe('#currency', function() {
  return context('default currency', function() {
    var amount, c, i, results;
    amount = (function() {
      results = [];
      for (i = 10; i <= 100; i++){ results.push(i); }
      return results;
    }).apply(this);
    c = Phil.currency(amount);
    it('returns a string with a dollar value', function() {
      return expect(c).toStartWith('$');
    });
    it("returns a dollar value within 10..100", function() {
      return expect(amount).toCover(c.replace(/\$/g, "") - 0);
    });
    it("formats the currency to two decimal places", function() {
      return expect(c).toMatch(/\$\d{2}\.\d{2}/);
    });
    return it("starts with a money symbol", function() {
      var cc, symbol;
      symbol = Phil.pick(["EUR ", "RMB ", "CAN $"]);
      cc = Phil.currency(amount, symbol);
      return expect(cc).toStartWith(symbol);
    });
  });
});
