// Generated by CoffeeScript 1.12.7
var Phil, expect;

Phil = require('../Phil');

if (typeof expect === "undefined" || expect === null) {
  expect = Phil.expect;
}

describe('Phil.image', function() {
  it('should use placeholder images', function() {
    expect(Phil.image(200)).toEqual('http://placehold.it/200');
    expect(Phil.image('200x100')).toEqual('http://placehold.it/200x100');
    expect(Phil.image('200x100', '#ff0000')).toEqual('http://placehold.it/200x100/ff0000');
    expect(Phil.image(200, 'parachute&pants:% are they; the best?')).toEqual('http://placehold.it/200&text=parachute+pants:+are+they;+the+best');
    return expect(Phil.image('#fff', 'no size')).toEqual(void 0);
  });
  it('parameters can be passed by name', function() {
    var args;
    args = {
      width: 200,
      height: 100,
      background: '#000',
      foreground: '#fff',
      text: 'pants'
    };
    return expect(Phil.image(args)).toEqual('http://placehold.it/200x100/000/fff&text=pants');
  });
  it('dims specified in range', function() {
    var i, j, k, l, range_matches, results, results1, results2, results3, subject;
    subject = Phil.image({
      width: (function() {
        results = [];
        for (i = 100; i <= 200; i++){ results.push(i); }
        return results;
      }).apply(this),
      height: (function() {
        results1 = [];
        for (j = 300; j <= 400; j++){ results1.push(j); }
        return results1;
      }).apply(this)
    });
    range_matches = subject.match(/http:\/\/placehold\.it\/(\d+)x(\d+)/);
    expect((function() {
      results2 = [];
      for (k = 100; k <= 200; k++){ results2.push(k); }
      return results2;
    }).apply(this)).toCover(+range_matches[1]);
    return expect((function() {
      results3 = [];
      for (l = 300; l <= 400; l++){ results3.push(l); }
      return results3;
    }).apply(this)).toCover(+range_matches[2]);
  });
  return this;
});

describe('image2', function() {
  var Subject;
  Subject = function() {
    return Phil.image.apply(Phil, arguments);
  };
  it('only one dimension specified', function() {
    var subject;
    subject = Subject(200);
    return it('outputs a valid placeholder url', function() {
      return expect(subject).toEqual('http://placehold.it/200');
    });
  });
  return context('strips illegal characters', function() {
    var subject;
    subject = Subject(200, 'parachute&pants:% are they; the best?');
    return it('outputs a valid placeholder url', function() {
      return expect(subject).toEqual('http://placehold.it/200&text=parachute+pants:+are+they;+the+best');
    });
  });
});
