// Generated by CoffeeScript 1.12.7
var Faker, Phil, build_tag, build_tags, format_image_argument_output, html_safe, parse_image_arguments, pick, rand, tag,
  hasProp = {}.hasOwnProperty;

if (typeof require === "function") {
  Faker = require('@faker-js/faker').faker;
}

html_safe = function(s) {
  return String(s).replace(/&/g, "&amp;").replace(/</g, '&lt;').replace(/>/g, '&gt;');
};

parse_image_arguments = function(obj) {
  var arg, argu, j, k, len1, output, v;
  output = {};
  if (obj && typeof obj === "object") {
    for (k in obj) {
      if (!hasProp.call(obj, k)) continue;
      v = obj[k];
      output[k] = v;
    }
  }
  for (j = 0, len1 = arguments.length; j < len1; j++) {
    argu = arguments[j];
    arg = argu.toString();
    switch (false) {
      case !arg.match(/^(#[a-f\d]{3,6}(\/(?=#))?){1,2}$/):
        output['color'] = arg;
        break;
      case !arg.match(/^([\d\.]*)x?([\d\.]*?)$/):
        output['size'] = arg;
        break;
      default:
        if (obj !== argu) {
          output['text'] = arg;
        }
    }
  }
  return output;
};

format_image_argument_output = function(args) {
  var k, v;
  if (!args['color']) {
    args['color'] = "" + (args['background'] || '') + (args['foreground'] || '');
  }
  if (args['width'] && args['height']) {
    args['size'] = (Phil.pick(args['width'])) + "x" + (Phil.pick(args['height']));
  }
  for (k in args) {
    v = args[k];
    switch (k) {
      case "color":
        args[k] = v.replace(/\/?#/g, '/');
        break;
      case "text":
        args['text'] = "&text=" + (v.replace(/[^\d\w\!,\.;:-]+/g, '+').replace(/\+?$/g, ''));
    }
  }
  return args;
};

rand = function(n) {
  if (n == null) {
    n = 10;
  }
  return Math.floor(Math.random() * n);
};

Phil = (function() {
  function Phil() {}

  return Phil;

})();

Phil.rand = rand;

pick = Phil.pick = function(num) {
  if (num.length && !num.charCodeAt) {
    return num[Math.floor(Math.random() * num.length)];
  }
  return num;
};

Phil.loop = function(num, fn) {
  var i, j, ref;
  for (i = j = 0, ref = pick(num) - 1; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
    fn(i);
  }
  return i;
};


/** Private */

build_tags = function(name, content, elements) {
  var content_method, times, x;
  if (elements == null) {
    elements = 1;
  }
  content_method = typeof content === "function" ? content : function() {
    return Phil.words(content);
  };
  times = pick(elements);
  return ((function() {
    var j, ref, results;
    results = [];
    for (x = j = 1, ref = times; 1 <= ref ? j <= ref : j >= ref; x = 1 <= ref ? ++j : --j) {
      results.push(build_tag(name, content_method));
    }
    return results;
  })()).join('');
};

build_tag = function(name, content) {
  return "<" + name + ">" + ((typeof content === "function" ? content() : void 0) || content) + "</" + name + ">";
};

tag = function(name, content, children) {
  switch (name) {
    case "ul":
    case "ol":
      content || (content = [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]);
      children || (children = [3, 4, 5, 6, 7, 8, 9, 10]);
      return build_tag(name, build_tags("li", content, children));
    case "blockquote":
      content || (content = [1, 2, 3]);
      return build_tag(name, Phil.paragraphs(content));
    case "p":
      return Phil.paragraphs(1);
    default:
      content || (content = [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]);
      return build_tags(name, content);
  }
};

Phil.image = function() {
  var opts;
  opts = format_image_argument_output(parse_image_arguments.apply(Phil, arguments));
  return opts['size'] && ("http://placehold.it/" + opts['size'] + (opts['color'] || '') + (opts['text'] || ''));
};

Phil.words = function(num) {
  if (num == null) {
    num = Phil.range(5, 20);
  }
  return html_safe(Faker.lorem.words(Phil.pick(num)));
};

Phil.paragraphs = function(num) {
  var content_method;
  if (num == null) {
    num = Phil.range(1, 3);
  }
  content_method = function() {
    return Faker.lorem.paragraphs(1);
  };
  return build_tags("p", content_method, pick(num));
};

Phil.blockquote = function(paragraphs) {
  return tag("blockquote", paragraphs);
};

Phil.ul = function(list_items, item_length) {
  return tag("ul", item_length, list_items);
};

Phil.ol = function(list_items, item_length) {
  return tag("ol", item_length, list_items);
};

Phil.link_list = function(list_items, item_length) {
  if (list_items == null) {
    list_items = [3, 4, 5, 6, 7, 8, 9, 10];
  }
  if (item_length == null) {
    item_length = [1, 2, 3, 4, 5];
  }
  return build_tag("ul", build_tags("li", (function() {
    return "<a href='#'>" + (Phil.words(item_length)) + "</a>";
  }), list_items));
};

Phil.markup = function(pattern) {
  if (pattern == null) {
    pattern = "h1 p p h2 p ol h2 p ul";
  }
  return pattern.split(" ").map(function(t) {
    return tag(t);
  }).join('\n');
};

Phil.currency = function(num, symbol) {
  var val;
  if (num == null) {
    num = Phil.range(1, 10000) / 100;
  }
  if (symbol == null) {
    symbol = "$";
  }
  val = ((pick(num) * 100) / 100).toFixed(2);
  return symbol + val;
};

Phil.number = function(len) {
  var j, results;
  return (function() {
    results = [];
    for (var j = 1; 1 <= len ? j <= len : j >= len; 1 <= len ? j++ : j--){ results.push(j); }
    return results;
  }).apply(this).map(function() {
    return rand(10);
  }).join('');
};

Phil.phone = function(format) {
  if (format == null) {
    format = "(###) ###-####";
  }
  return format.replace(/#/g, function() {
    return rand(9) + 1;
  });
};

Phil.date = function(day_window) {
  var t;
  t = (typeof Date.now === "function" ? Date.now() : void 0) || new Date().getTime();
  return new Date(day_window ? t - rand(day_window) * 86400000 : rand(t));
};

Phil.city = function() {
  return Faker.location.city();
};

Phil.domainName = function() {
  return Faker.internet.domainName();
};

Phil.email = function() {
  return Faker.internet.email();
};

Phil.firstName = function() {
  return Faker.person.firstName();
};

Phil.lastName = function() {
  return Faker.person.lastName();
};

Phil.name = function() {
  return Faker.person.name();
};

Phil.state = function() {
  return Faker.location.state();
};

Phil.state_abbr = function() {
  return Faker.location.state({
    abbreviated: true
  });
};

Phil.body_content = Phil.markup;

Phil.sometimes = function(num_or_content, num) {
  var fn, j, l, results, results1;
  if (num_or_content == null) {
    num_or_content = 3;
  }
  if (num == null) {
    num = 3;
  }
  fn = arguments[arguments.length - 1];
  if (typeof fn === "function") {
    if (typeof num_or_content === "function") {
      num_or_content = 3;
    }
    if (typeof num === "function") {
      num = 3;
    }
    if (num_or_content === Phil.pick((function() {
      results = [];
      for (var j = 1; 1 <= num_or_content ? j <= num_or_content : j >= num_or_content; 1 <= num_or_content ? j++ : j--){ results.push(j); }
      return results;
    }).apply(this))) {
      return fn(num_or_content, num);
    }
  } else {
    if (num === Phil.pick((function() {
      results1 = [];
      for (var l = 1; 1 <= num ? l <= num : l >= num; 1 <= num ? l++ : l--){ results1.push(l); }
      return results1;
    }).apply(this))) {
      return num_or_content;
    }
  }
};

Phil.reload = function(lastmod) {
  if (lastmod == null) {
    lastmod = '.';
  }
  require.cache[require.resolve(lastmod)] = void 0;
  return require(lastmod);
};

Phil.range = function(low, high) {
  if (high == null) {
    high = low != null ? low : 10;
    low = 0;
  }
  return Math.round(low + Math.random() * (high - low));
};

if (typeof module !== "undefined" && module !== null ? module.exports : void 0) {
  module.exports = Phil;
}
